# Generated by Django 3.2.18 on 2023-06-11 09:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('website', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='NursingSamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_file', models.FileField(upload_to='')),
                ('sample_title', models.CharField(blank=True, max_length=200)),
                ('sample_type', models.CharField(blank=True, max_length=200)),
                ('sample_pages', models.IntegerField(default=1, null=True)),
                ('sample_body', models.TextField(blank=True)),
                ('sample_urgency', models.IntegerField(default=1, null=True)),
                ('sample_academic_level', models.TextField(blank=True)),
                ('sample_style', models.TextField(blank=True, max_length=5000)),
                ('sample_sources', models.IntegerField(default=1, null=True)),
                ('sample_subject_area', models.CharField(max_length=50)),
                ('sample_price', models.IntegerField(default=0)),
                ('sample_writer_level', models.CharField(max_length=50, null=True)),
                ('sample_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NursingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.order')),
            ],
        ),
        migrations.CreateModel(
            name='NursingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.order')),
            ],
        ),
    ]
