# Generated by Django 3.2.18 on 2023-06-11 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField(default=100, null=True)),
                ('order_type', models.CharField(max_length=50)),
                ('subject_area', models.CharField(max_length=50)),
                ('academic_level', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
                ('pages', models.IntegerField(null=True)),
                ('spacing', models.CharField(max_length=50)),
                ('sources', models.IntegerField(default=1, null=True)),
                ('style', models.CharField(max_length=50)),
                ('writer_level', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Not_Paid', 'Not Paid'), ('Paid', 'Paid'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Bidding', 'Bidding'), ('Assigned', 'Assigned'), ('Editing', 'Editing'), ('Revision', 'Revision'), ('In_Progress', 'In Progress'), ('Cancelled', 'Cancelled')], default='Not_Paid', max_length=50)),
                ('website', models.CharField(choices=[('Birdie', 'Birdie'), ('Nursing', 'Nursing'), ('EXP', 'EXP')], default='Birdie', max_length=50)),
                ('Submissiondate', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(max_length=250)),
                ('new_deadline', models.DateTimeField(null=True)),
                ('UpdationDate', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('writer_amount', models.IntegerField(default=1, null=True)),
                ('editor_amount', models.IntegerField(default=1, null=True)),
                ('net_amount', models.IntegerField(default=1, null=True)),
                ('writer_time', models.DateTimeField(null=True)),
                ('rating', models.IntegerField(default=1, null=True)),
                ('transaction_id', models.IntegerField(default=100000000, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='admindash.client')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpers', to='admindash.editor')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.order')),
            ],
        ),
        migrations.CreateModel(
            name='Ordertracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=250)),
                ('UpdationDate', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=1, null=True)),
                ('new_deadline', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindash.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admindash.order')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birdies', to='admindash.writer'),
        ),
        migrations.CreateModel(
            name='Dashorderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.IntegerField(default=1, null=True)),
                ('writer_amount', models.IntegerField(default=1, null=True)),
                ('editor_amount', models.IntegerField(default=1, null=True)),
                ('net_amount', models.IntegerField(default=1, null=True)),
                ('status', models.CharField(choices=[('Not_Paid', 'Not Paid'), ('Paid', 'Paid'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Bidding', 'Bidding'), ('Assigned', 'Assigned'), ('Editing', 'Editing'), ('Revision', 'Revision'), ('In_Progress', 'In Progress'), ('Cancelled', 'Cancelled')], max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.order')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('writer', 'Writer'), ('client', 'Client'), ('support', 'Support/Editor')], default='client', max_length=10)),
                ('recipient_type', models.CharField(choices=[('writer', 'Writer'), ('client', 'Client'), ('support', 'Support/Editor')], default='client', max_length=10)),
                ('body', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.order')),
                ('recipient_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='chat_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_status', models.CharField(default='draft', max_length=50)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_editor', to='admindash.editor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminfiles', to='admindash.order')),
            ],
        ),
    ]
