# Generated by Django 3.2.18 on 2023-06-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdieOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.order')),
            ],
        ),
    ]
